
//拍圈列表
export const FETCH_SHOOT_LIST = 'FETCH_SHOOT_LIST';
export const RECEIVED_SHOOT_LIST = 'RECEIVED_SHOOT_LIST';
export const FETCH_SHOOT_LIST_ERROR = 'FETCH_SHOOT_LIST_ERROR';
//拍圈类别
export const FETCH_SHOOT_TYPE = 'FETCH_SHOOT_TYPE';
export const RECEIVED_SHOOT_TYPE = 'RECEIVED_SHOOT_TYPE';
export const FETCH_SHOOT_TYPE_ERROR = 'FETCH_SHOOT_TYPE_ERROR';